apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
  - image: fra.ocir.io/arrow2020/lukaszro/springboot-demo:0.0.1-SNAPSHOT
    jibGradle: {}
  local:
    push: true
deploy:
  helm:
    releases:
      - name: spring-demo
        chartPath: helm/springboot-demo
        namespace: default
        recreatePods: true
        values:
          image: fra.ocir.io/arrow2020/lukaszro/springboot-demo:0.0.1-SNAPSHOT
        valuesFiles: ["helm/oke-values.yaml"]