apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-demo-config
data:
  application.properties: |-
    demo.name=Kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-springboot-demo
  labels:
    run: rest-springboot-demo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: rest-springboot-demo
  template:
    metadata:
      labels:
        run: rest-springboot-demo
    spec:
      containers:
        - image: springboot-demo:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          name: rest-springboot-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: application-config
              readOnly: true
      imagePullSecrets:
        - name: wrelease
      restartPolicy: Always
      volumes:
        - name: application-config
          configMap:
            name: springboot-demo-config
            optional: true
            items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: rest-springboot-demo-svc
spec:
  selector:
    run: rest-springboot-demo
  ports:
    - port: 8088
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rest-springboot-demo-ing
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    ingress.kubernetes.io/add-base-url: 'true'
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /lukaszro/
        backend:
          serviceName: rest-springboot-demo-svc
          servicePort: 8088