apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-demo.fullname" . }}
  labels:
    app: {{ include "springboot-demo.name" . }}
    chart: {{ include "springboot-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "springboot-demo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "springboot-demo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: DEMO_NAME
              valueFrom:
                secretKeyRef:
                  key: demo_name
                  name: {{ include "springboot-demo.fullname" . }}-app-secret
          volumeMounts:
            - mountPath: /config
              name: application-config
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: {{ include "springboot-demo.fullname" . }}-config-map
            optional: true
            items:
              - key: application.properties
                path: application.properties
