apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot-demo.fullname" . }}-app-secret
type: Opaque
data:
  demo_name: {{ .Values.demo.name | b64enc }}
# an alternative for taking secret data from files (bar directory):
#{{ (.Files.Glob "bar/*").AsSecrets | indent 2 }}