image:
  repository: fra.ocir.io/arrow2020/lukaszro/springboot-demo
  tag: 0.0.1-SNAPSHOT
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: '/$1'
  path: /oke-demo/(.+)

app:
  port: 8080

demo:
  name: James Bond
  greeting: Salut